### ISSUE TITLE
Warning about global

### ISSUE THREAD

**Issue by wprl** [elrasguno/npm-update-outdated#1]
Thanks for creating this, it was exactly what i was looking for.

I saw the warning about preferring global installation when installing this.  It doesn't bother me but some people don't like to see any kind of warning and when I talk to them I like to avoid such contentious conversations.  

I prefer to not install globally because then I can have everything in a nice bundle and run from `node_modules/.bin/npm-update-outdated`.  Is there any specific reason not to do this (for example, does it break the module)?    If not, would it be possible to disable this warning?

**Comment by elrasguno** [comment]
That's a fine suggestion! I'll have a new version for you in a day or two with a few new features.

**Comment by elrasguno** [comment]
npm-update-outdated v0.1.4
 * Removed "preferGlobal" property per suggestion in #1
 * Added optional --save, --save-dev, --save-exact, and --save-optional aptions
