### ISSUE TITLE
--missing flag doesn't seem to work

### ISSUE THREAD

**Issue by mzimin** [elrasguno/npm-update-outdated#2]
When I run
`npm outdated` 
I get a lot of packages listed as MISSING but when I run
`npm-update-outdated` 
or
`npm-update-outdated  --missing`
I just get
`All your NPM modules are up to date. You rule!` 
and nothing is installed

npm version is 2.5.1

**Comment by elrasguno** [comment]
I will take a look! Thanks for posting the issue.

**Comment by elrasguno** [comment]
Ahh, note that if the missing modules are _not_ at the top level, the _--missing_ flag doesn't support that, yet.

**Comment by elrasguno** [comment]
Sorry for the long lag. Fixed it!
