### ISSUE TITLE
Can you add a --check-only flag?

### ISSUE THREAD

**Issue by guyellis** [elrasguno/npm-update-outdated#3]
My use case: As part of a pre-commit set of scripts that run I use this module `npm-updated-outdated` to first update all modules and then run the tests etc. Makes sense right? Here's an example: https://github.com/guyellis/http-status-check/blob/master/package.json#L19

On the above project the only way to check non-explicit versions is to do an npm update. On some projects we have explicit versions against all dependencies. The only time we need this check to fail is when the package.json doesn't match what is in node_modules or is missing in node_modules or is extra in node_modules.

The drawback to using `npm-updated-outdated` is that in this use case it takes too long to run. I was wondering if you could add a `--check-only` or `--check-explicit-only` flag that looked at the package.json dependencies and at the installed modules and failed only if they didn't match. This would obviously run really fast compared to the regular functionality of this module and would add great value to that type of project.

This helps when a member of the team pulls down the latest code (from say the master branch) and forgets to do an `npm update`. The first time they run this script the pre-tests would fail letting them know to run `npm-update-outdated`. As a bonus there would be another flag to say automatically run `npm-update-outdated` if the --check-only flag fails.

**Comment by elrasguno** [comment]
Thanks for the request, guy! I'll consider the additional flag to automatically update when outdated sooner than later.

**Comment by guyellis** [comment]
:+1:
